# Site settings
title: Anthony Rios
email: anthony.rios@utsa.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonymrios.net" # the base hostname & protocol for your site
twitter_username: anthonymrios
github_username: AnthonyMRios
linkedin_username: anthonyrios0
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
